schema.vertexLabel('user').ifNotExists()
    .partitionBy('id', Uuid)
    .property('name', Text)
    .property('username', Varchar)
    .property('birthday', Date)    
    .property('email', Text)
    .property('password', Text)
    .property('avatar', Text)
    .property('status', Boolean)
    .property('created_at', Date)
    .create()

schema.vertexLabel('group_chat').ifNotExists()
    .partitionBy('id', Uuid)
    .property('name', Text)
    .property('photo', Text)
    .property('messages', listOf(Uuid))
    .create()

schema.edgeLabel('include').ifNotExists()
    .from('group_chat').to('user')
    .property('role', Text) // 0: member 1: admin
    .property('nickname', Varchar)
    .create()

schema.edgeLabel('communicate').ifNotExists()
    .from('user').to('user')
    .property('type', Text) // Loại mối quan hệ (ví dụ: friendship, follow, block, subscribe, waiting,...)
    .property('since', Date)
    .property('is_read', Boolean)
    .property('messages', listOf(Uuid))
    .create()