export enum ExceptionStrings {
  UNKNOWN_MESSAGE = 'Unknown message.',
  UNKNOWN_USER = 'Unknown user.',
  UNKNOWN_CHANNEL = 'Unknown channel.',
  UNKNOWN_INVITE = 'Unknown invite.',
  PASSWORD_INCORRECT = 'Password is incorrect.',
  PASSWORD_REQUIRED_CRED_UPDATE = 'Password is required when changing password.',
  PASSWORD_REQUIRED_EMAIL_UPDATE = 'Password is required when changing email.',
  ALREADY_MEMBER = 'User is already a channel member.',
  NOT_MEMBER = 'User is not a channel member.',
  NOT_OWNER = 'User is not channel owner.',
  USERNAME_EXISTS = 'Such username already exist.',
  CHANNEL_EXISTS = 'Such channel already exists.',
  INVITE_EXISTS = 'Such invite already exists.',
  EMAIL_EXISTS = 'Such email already exists.',
  REQUEST_ALREADY_SENT = 'You have already sent a friend request to this user.',
  REQUEST_ALREADY_RECEIVED = 'You have an incoming friend request from this user.',
  REQUEST_ALREADY_FRIENDS = 'You are already friends with this user.',
  REQUEST_ACCEPT_SELF = 'You cannot accept your own friend request.',
  BLOCKED_TO = 'You have blocked this user.',
  BLOCKED_FROM = 'This user has blocked you.',
  NOT_FRIENDS = 'You are not friends with this user.',
  NO_REQUEST_TO = "You don't have a pending friend request to this user.",
  NO_REQUEST_FROM = "You don't have a pending friend request from this user.",
  TOKEN_REQUIRED = 'Token is required.'
}
